export const PRODUCT = {
    PRESS_ADD_NEW_CATEGORY: 'PRESS_ADD_NEW_CATEGORY',
    SET_FIELD_INPUT: 'SET_FIELD_INPUT',
    PRESS_ADD_NEW_FIELD: 'PRESS_ADD_NEW_FIELD',
    SET_TITLE: 'SET_TITLE',
    REMOVE_CATEGORY: 'REMOVE_CATEGORY',
    REMOVE_CATEGORY_FIELD: 'REMOVE_CATEGORY_FIELD',
    ADD_CATEGORY_ITEM: 'ADD_CATEGORY_ITEM',
    SET_PRODUCT_VALUE_INPUT: 'SET_PRODUCT_VALUE_INPUT',
    REMOVE_CATEGORY_PRODUCT: 'REMOVE_CATEGORY_PRODUCT'
};
